/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface GroupingInterface extends ethers.utils.Interface {
  functions: {
    "assets(uint256)": FunctionFragment;
    "operators(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "rgToken()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "approveOperator(address)": FunctionFragment;
    "isOperatorApproved(address)": FunctionFragment;
    "addAsset(uint256)": FunctionFragment;
    "isAssetAdded(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "assets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "rgToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "approveOperator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperatorApproved",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addAsset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAssetAdded",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "assets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rgToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperatorApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAssetAdded",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class Grouping extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: GroupingInterface;

  functions: {
    assets(arg0: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    "assets(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    /**
     * operators are the erc721 owners that have been approved in this
     */
    operators(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    /**
     * operators are the erc721 owners that have been approved in this
     */
    "operators(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    /**
     * Tells the address of the owner return the address of the owner
     */
    owner(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Tells the address of the owner return the address of the owner
     */
    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    rgToken(overrides?: CallOverrides): Promise<[string]>;

    "rgToken()"(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    approveOperator(
      _operator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approveOperator(address)"(
      _operator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isOperatorApproved(
      _operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isOperatorApproved(address)"(
      _operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    addAsset(
      _asset: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addAsset(uint256)"(
      _asset: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isAssetAdded(
      _asset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isAssetAdded(uint256)"(
      _asset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  assets(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  "assets(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  /**
   * operators are the erc721 owners that have been approved in this
   */
  operators(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  /**
   * operators are the erc721 owners that have been approved in this
   */
  "operators(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  /**
   * Tells the address of the owner return the address of the owner
   */
  owner(overrides?: CallOverrides): Promise<string>;

  /**
   * Tells the address of the owner return the address of the owner
   */
  "owner()"(overrides?: CallOverrides): Promise<string>;

  rgToken(overrides?: CallOverrides): Promise<string>;

  "rgToken()"(overrides?: CallOverrides): Promise<string>;

  /**
   * Allows the current owner to transfer control of the contract to a newOwner.
   * @param newOwner The address to transfer ownership to.
   */
  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows the current owner to transfer control of the contract to a newOwner.
   * @param newOwner The address to transfer ownership to.
   */
  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  approveOperator(
    _operator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approveOperator(address)"(
    _operator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isOperatorApproved(
    _operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isOperatorApproved(address)"(
    _operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  addAsset(
    _asset: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addAsset(uint256)"(
    _asset: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isAssetAdded(
    _asset: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isAssetAdded(uint256)"(
    _asset: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    assets(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "assets(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * operators are the erc721 owners that have been approved in this
     */
    operators(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    /**
     * operators are the erc721 owners that have been approved in this
     */
    "operators(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    /**
     * Tells the address of the owner return the address of the owner
     */
    owner(overrides?: CallOverrides): Promise<string>;

    /**
     * Tells the address of the owner return the address of the owner
     */
    "owner()"(overrides?: CallOverrides): Promise<string>;

    rgToken(overrides?: CallOverrides): Promise<string>;

    "rgToken()"(overrides?: CallOverrides): Promise<string>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    approveOperator(
      _operator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "approveOperator(address)"(
      _operator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isOperatorApproved(
      _operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isOperatorApproved(address)"(
      _operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addAsset(_asset: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    "addAsset(uint256)"(
      _asset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isAssetAdded(
      _asset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isAssetAdded(uint256)"(
      _asset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    OwnershipTransferred(previousOwner: null, newOwner: null): EventFilter;
  };

  estimateGas: {
    assets(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "assets(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * operators are the erc721 owners that have been approved in this
     */
    operators(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * operators are the erc721 owners that have been approved in this
     */
    "operators(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Tells the address of the owner return the address of the owner
     */
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Tells the address of the owner return the address of the owner
     */
    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    rgToken(overrides?: CallOverrides): Promise<BigNumber>;

    "rgToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    approveOperator(
      _operator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "approveOperator(address)"(
      _operator: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isOperatorApproved(
      _operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isOperatorApproved(address)"(
      _operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addAsset(_asset: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "addAsset(uint256)"(
      _asset: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isAssetAdded(
      _asset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isAssetAdded(uint256)"(
      _asset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    assets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "assets(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * operators are the erc721 owners that have been approved in this
     */
    operators(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * operators are the erc721 owners that have been approved in this
     */
    "operators(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Tells the address of the owner return the address of the owner
     */
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Tells the address of the owner return the address of the owner
     */
    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rgToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "rgToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    approveOperator(
      _operator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approveOperator(address)"(
      _operator: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isOperatorApproved(
      _operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isOperatorApproved(address)"(
      _operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addAsset(
      _asset: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addAsset(uint256)"(
      _asset: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isAssetAdded(
      _asset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isAssetAdded(uint256)"(
      _asset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
