/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MultiSigHashedInterface extends ethers.utils.Interface {
  functions: {
    "MAX_OWNER_COUNT()": FunctionFragment;
    "confirmations(bytes32,address)": FunctionFragment;
    "hashes(uint256)": FunctionFragment;
    "isOwner(address)": FunctionFragment;
    "owners(uint256)": FunctionFragment;
    "required()": FunctionFragment;
    "transactionCount()": FunctionFragment;
    "transactions(bytes32)": FunctionFragment;
    "ownerHasConfirmed(bytes32,address)": FunctionFragment;
    "addOwner(address)": FunctionFragment;
    "removeOwner(address)": FunctionFragment;
    "replaceOwner(address,address)": FunctionFragment;
    "changeRequirement(uint256)": FunctionFragment;
    "submitTransaction(address,uint256,bytes)": FunctionFragment;
    "confirmTransaction(bytes32)": FunctionFragment;
    "revokeConfirmation(bytes32)": FunctionFragment;
    "executeTransaction(bytes32)": FunctionFragment;
    "isConfirmed(bytes32)": FunctionFragment;
    "makeHash(address,uint256,bytes)": FunctionFragment;
    "getConfirmationCount(bytes32)": FunctionFragment;
    "getOwners()": FunctionFragment;
    "getConfirmations(bytes32)": FunctionFragment;
    "getTransaction(bytes32)": FunctionFragment;
    "getTransactionByIdx(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MAX_OWNER_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confirmations",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "owners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "required", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transactionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerHasConfirmed",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "addOwner", values: [string]): string;
  encodeFunctionData(functionFragment: "removeOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "replaceOwner",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeRequirement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTransaction",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmTransaction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeConfirmation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isConfirmed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "makeHash",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfirmationCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getOwners", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getConfirmations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransaction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionByIdx",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_OWNER_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hashes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owners", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "required", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerHasConfirmed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replaceOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeConfirmation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConfirmed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "makeHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getConfirmationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionByIdx",
    data: BytesLike
  ): Result;

  events: {
    "Confirmation(address,bytes32)": EventFragment;
    "Deposit(address,uint256)": EventFragment;
    "Execution(bytes32)": EventFragment;
    "ExecutionFailure(bytes32)": EventFragment;
    "OwnerAddition(address)": EventFragment;
    "OwnerRemoval(address)": EventFragment;
    "RequirementChange(uint256)": EventFragment;
    "Revocation(address,bytes32)": EventFragment;
    "Submission(bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Confirmation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Execution"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutionFailure"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerAddition"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerRemoval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequirementChange"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Revocation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Submission"): EventFragment;
}

export class MultiSigHashed extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MultiSigHashedInterface;

  functions: {
    MAX_OWNER_COUNT(overrides?: CallOverrides): Promise<[BigNumber]>;

    "MAX_OWNER_COUNT()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    confirmations(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "confirmations(bytes32,address)"(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "hashes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isOwner(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isOwner(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "owners(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    required(overrides?: CallOverrides): Promise<[BigNumber]>;

    "required()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    transactionCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    "transactionCount()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    transactions(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, boolean, BigNumber, string] & {
        destination: string;
        value: BigNumber;
        data: string;
        executed: boolean;
        timestamp: BigNumber;
        hash: string;
      }
    >;

    "transactions(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, boolean, BigNumber, string] & {
        destination: string;
        value: BigNumber;
        data: string;
        executed: boolean;
        timestamp: BigNumber;
        hash: string;
      }
    >;

    ownerHasConfirmed(
      hash: BytesLike,
      owner: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "ownerHasConfirmed(bytes32,address)"(
      hash: BytesLike,
      owner: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    /**
     * Allows to add a new owner. Transaction has to be sent by wallet.
     * @param owner Address of new owner to add.
     */
    addOwner(
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows to add a new owner. Transaction has to be sent by wallet.
     * @param owner Address of new owner to add.
     */
    "addOwner(address)"(
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows to remove an owner. Transaction has to be sent by wallet.
     * @param owner Address of owner to remove.
     */
    removeOwner(
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows to remove an owner. Transaction has to be sent by wallet.
     * @param owner Address of owner to remove.
     */
    "removeOwner(address)"(
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows to replace an owner with a new owner. Transaction has to be sent by wallet.
     * @param newOwner Address of new owner.
     * @param owner Address of owner to be replaced.
     */
    replaceOwner(
      owner: string,
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows to replace an owner with a new owner. Transaction has to be sent by wallet.
     * @param newOwner Address of new owner.
     * @param owner Address of owner to be replaced.
     */
    "replaceOwner(address,address)"(
      owner: string,
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows to change the number of required confirmations. Transaction has to be sent by wallet.
     * @param _required Number of required confirmations.
     */
    changeRequirement(
      _required: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows to change the number of required confirmations. Transaction has to be sent by wallet.
     * @param _required Number of required confirmations.
     */
    "changeRequirement(uint256)"(
      _required: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows an owner to submit and confirm a transaction.
     * @param data Transaction data payload.
     * @param destination Transaction target address.
     * @param value Transaction ether value.
     */
    submitTransaction(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows an owner to submit and confirm a transaction.
     * @param data Transaction data payload.
     * @param destination Transaction target address.
     * @param value Transaction ether value.
     */
    "submitTransaction(address,uint256,bytes)"(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows an owner to confirm a transaction.
     * @param hash Transaction ID.
     */
    confirmTransaction(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows an owner to confirm a transaction.
     * @param hash Transaction ID.
     */
    "confirmTransaction(bytes32)"(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows an owner to revoke a confirmation for a transaction.
     * @param hash Transaction ID.
     */
    revokeConfirmation(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows an owner to revoke a confirmation for a transaction.
     * @param hash Transaction ID.
     */
    "revokeConfirmation(bytes32)"(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows anyone to execute a confirmed transaction.
     * @param hash Transaction ID.
     */
    executeTransaction(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows anyone to execute a confirmed transaction.
     * @param hash Transaction ID.
     */
    "executeTransaction(bytes32)"(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Returns the confirmation status of a transaction.
     * @param hash Transaction ID.
     */
    isConfirmed(hash: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    /**
     * Returns the confirmation status of a transaction.
     * @param hash Transaction ID.
     */
    "isConfirmed(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    makeHash(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { hash: string }>;

    "makeHash(address,uint256,bytes)"(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { hash: string }>;

    /**
     * Returns number of confirmations of a transaction.
     * @param hash Transaction ID.
     */
    getConfirmationCount(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { count: BigNumber }>;

    /**
     * Returns number of confirmations of a transaction.
     * @param hash Transaction ID.
     */
    "getConfirmationCount(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { count: BigNumber }>;

    /**
     * Returns list of owners.
     */
    getOwners(overrides?: CallOverrides): Promise<[string[]]>;

    /**
     * Returns list of owners.
     */
    "getOwners()"(overrides?: CallOverrides): Promise<[string[]]>;

    /**
     * Returns array with owner addresses, which confirmed transaction.
     * @param hash Transaction ID.
     */
    getConfirmations(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]] & { _confirmations: string[] }>;

    /**
     * Returns array with owner addresses, which confirmed transaction.
     * @param hash Transaction ID.
     */
    "getConfirmations(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]] & { _confirmations: string[] }>;

    getTransaction(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, BigNumber, string, boolean, BigNumber, string] & {
          destination: string;
          value: BigNumber;
          data: string;
          executed: boolean;
          timestamp: BigNumber;
          hash: string;
        }
      ]
    >;

    "getTransaction(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, BigNumber, string, boolean, BigNumber, string] & {
          destination: string;
          value: BigNumber;
          data: string;
          executed: boolean;
          timestamp: BigNumber;
          hash: string;
        }
      ]
    >;

    getTransactionByIdx(
      idx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, BigNumber, string, boolean, BigNumber, string] & {
          destination: string;
          value: BigNumber;
          data: string;
          executed: boolean;
          timestamp: BigNumber;
          hash: string;
        }
      ]
    >;

    "getTransactionByIdx(uint256)"(
      idx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, BigNumber, string, boolean, BigNumber, string] & {
          destination: string;
          value: BigNumber;
          data: string;
          executed: boolean;
          timestamp: BigNumber;
          hash: string;
        }
      ]
    >;
  };

  MAX_OWNER_COUNT(overrides?: CallOverrides): Promise<BigNumber>;

  "MAX_OWNER_COUNT()"(overrides?: CallOverrides): Promise<BigNumber>;

  confirmations(
    arg0: BytesLike,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "confirmations(bytes32,address)"(
    arg0: BytesLike,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "hashes(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  isOwner(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "isOwner(address)"(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "owners(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  required(overrides?: CallOverrides): Promise<BigNumber>;

  "required()"(overrides?: CallOverrides): Promise<BigNumber>;

  transactionCount(overrides?: CallOverrides): Promise<BigNumber>;

  "transactionCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  transactions(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string, boolean, BigNumber, string] & {
      destination: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      timestamp: BigNumber;
      hash: string;
    }
  >;

  "transactions(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string, boolean, BigNumber, string] & {
      destination: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      timestamp: BigNumber;
      hash: string;
    }
  >;

  ownerHasConfirmed(
    hash: BytesLike,
    owner: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "ownerHasConfirmed(bytes32,address)"(
    hash: BytesLike,
    owner: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  /**
   * Allows to add a new owner. Transaction has to be sent by wallet.
   * @param owner Address of new owner to add.
   */
  addOwner(owner: string, overrides?: Overrides): Promise<ContractTransaction>;

  /**
   * Allows to add a new owner. Transaction has to be sent by wallet.
   * @param owner Address of new owner to add.
   */
  "addOwner(address)"(
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows to remove an owner. Transaction has to be sent by wallet.
   * @param owner Address of owner to remove.
   */
  removeOwner(
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows to remove an owner. Transaction has to be sent by wallet.
   * @param owner Address of owner to remove.
   */
  "removeOwner(address)"(
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows to replace an owner with a new owner. Transaction has to be sent by wallet.
   * @param newOwner Address of new owner.
   * @param owner Address of owner to be replaced.
   */
  replaceOwner(
    owner: string,
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows to replace an owner with a new owner. Transaction has to be sent by wallet.
   * @param newOwner Address of new owner.
   * @param owner Address of owner to be replaced.
   */
  "replaceOwner(address,address)"(
    owner: string,
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows to change the number of required confirmations. Transaction has to be sent by wallet.
   * @param _required Number of required confirmations.
   */
  changeRequirement(
    _required: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows to change the number of required confirmations. Transaction has to be sent by wallet.
   * @param _required Number of required confirmations.
   */
  "changeRequirement(uint256)"(
    _required: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows an owner to submit and confirm a transaction.
   * @param data Transaction data payload.
   * @param destination Transaction target address.
   * @param value Transaction ether value.
   */
  submitTransaction(
    destination: string,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows an owner to submit and confirm a transaction.
   * @param data Transaction data payload.
   * @param destination Transaction target address.
   * @param value Transaction ether value.
   */
  "submitTransaction(address,uint256,bytes)"(
    destination: string,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows an owner to confirm a transaction.
   * @param hash Transaction ID.
   */
  confirmTransaction(
    hash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows an owner to confirm a transaction.
   * @param hash Transaction ID.
   */
  "confirmTransaction(bytes32)"(
    hash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows an owner to revoke a confirmation for a transaction.
   * @param hash Transaction ID.
   */
  revokeConfirmation(
    hash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows an owner to revoke a confirmation for a transaction.
   * @param hash Transaction ID.
   */
  "revokeConfirmation(bytes32)"(
    hash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows anyone to execute a confirmed transaction.
   * @param hash Transaction ID.
   */
  executeTransaction(
    hash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows anyone to execute a confirmed transaction.
   * @param hash Transaction ID.
   */
  "executeTransaction(bytes32)"(
    hash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Returns the confirmation status of a transaction.
   * @param hash Transaction ID.
   */
  isConfirmed(hash: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  /**
   * Returns the confirmation status of a transaction.
   * @param hash Transaction ID.
   */
  "isConfirmed(bytes32)"(
    hash: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  makeHash(
    destination: string,
    value: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "makeHash(address,uint256,bytes)"(
    destination: string,
    value: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  /**
   * Returns number of confirmations of a transaction.
   * @param hash Transaction ID.
   */
  getConfirmationCount(
    hash: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  /**
   * Returns number of confirmations of a transaction.
   * @param hash Transaction ID.
   */
  "getConfirmationCount(bytes32)"(
    hash: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  /**
   * Returns list of owners.
   */
  getOwners(overrides?: CallOverrides): Promise<string[]>;

  /**
   * Returns list of owners.
   */
  "getOwners()"(overrides?: CallOverrides): Promise<string[]>;

  /**
   * Returns array with owner addresses, which confirmed transaction.
   * @param hash Transaction ID.
   */
  getConfirmations(
    hash: BytesLike,
    overrides?: CallOverrides
  ): Promise<string[]>;

  /**
   * Returns array with owner addresses, which confirmed transaction.
   * @param hash Transaction ID.
   */
  "getConfirmations(bytes32)"(
    hash: BytesLike,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getTransaction(
    hash: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string, boolean, BigNumber, string] & {
      destination: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      timestamp: BigNumber;
      hash: string;
    }
  >;

  "getTransaction(bytes32)"(
    hash: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string, boolean, BigNumber, string] & {
      destination: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      timestamp: BigNumber;
      hash: string;
    }
  >;

  getTransactionByIdx(
    idx: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string, boolean, BigNumber, string] & {
      destination: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      timestamp: BigNumber;
      hash: string;
    }
  >;

  "getTransactionByIdx(uint256)"(
    idx: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string, boolean, BigNumber, string] & {
      destination: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      timestamp: BigNumber;
      hash: string;
    }
  >;

  callStatic: {
    MAX_OWNER_COUNT(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_OWNER_COUNT()"(overrides?: CallOverrides): Promise<BigNumber>;

    confirmations(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "confirmations(bytes32,address)"(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "hashes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    isOwner(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "isOwner(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "owners(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    required(overrides?: CallOverrides): Promise<BigNumber>;

    "required()"(overrides?: CallOverrides): Promise<BigNumber>;

    transactionCount(overrides?: CallOverrides): Promise<BigNumber>;

    "transactionCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    transactions(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, boolean, BigNumber, string] & {
        destination: string;
        value: BigNumber;
        data: string;
        executed: boolean;
        timestamp: BigNumber;
        hash: string;
      }
    >;

    "transactions(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, boolean, BigNumber, string] & {
        destination: string;
        value: BigNumber;
        data: string;
        executed: boolean;
        timestamp: BigNumber;
        hash: string;
      }
    >;

    ownerHasConfirmed(
      hash: BytesLike,
      owner: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "ownerHasConfirmed(bytes32,address)"(
      hash: BytesLike,
      owner: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    /**
     * Allows to add a new owner. Transaction has to be sent by wallet.
     * @param owner Address of new owner to add.
     */
    addOwner(owner: string, overrides?: CallOverrides): Promise<void>;

    /**
     * Allows to add a new owner. Transaction has to be sent by wallet.
     * @param owner Address of new owner to add.
     */
    "addOwner(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows to remove an owner. Transaction has to be sent by wallet.
     * @param owner Address of owner to remove.
     */
    removeOwner(owner: string, overrides?: CallOverrides): Promise<void>;

    /**
     * Allows to remove an owner. Transaction has to be sent by wallet.
     * @param owner Address of owner to remove.
     */
    "removeOwner(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows to replace an owner with a new owner. Transaction has to be sent by wallet.
     * @param newOwner Address of new owner.
     * @param owner Address of owner to be replaced.
     */
    replaceOwner(
      owner: string,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows to replace an owner with a new owner. Transaction has to be sent by wallet.
     * @param newOwner Address of new owner.
     * @param owner Address of owner to be replaced.
     */
    "replaceOwner(address,address)"(
      owner: string,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows to change the number of required confirmations. Transaction has to be sent by wallet.
     * @param _required Number of required confirmations.
     */
    changeRequirement(
      _required: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows to change the number of required confirmations. Transaction has to be sent by wallet.
     * @param _required Number of required confirmations.
     */
    "changeRequirement(uint256)"(
      _required: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows an owner to submit and confirm a transaction.
     * @param data Transaction data payload.
     * @param destination Transaction target address.
     * @param value Transaction ether value.
     */
    submitTransaction(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    /**
     * Allows an owner to submit and confirm a transaction.
     * @param data Transaction data payload.
     * @param destination Transaction target address.
     * @param value Transaction ether value.
     */
    "submitTransaction(address,uint256,bytes)"(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    /**
     * Allows an owner to confirm a transaction.
     * @param hash Transaction ID.
     */
    confirmTransaction(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows an owner to confirm a transaction.
     * @param hash Transaction ID.
     */
    "confirmTransaction(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows an owner to revoke a confirmation for a transaction.
     * @param hash Transaction ID.
     */
    revokeConfirmation(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows an owner to revoke a confirmation for a transaction.
     * @param hash Transaction ID.
     */
    "revokeConfirmation(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows anyone to execute a confirmed transaction.
     * @param hash Transaction ID.
     */
    executeTransaction(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows anyone to execute a confirmed transaction.
     * @param hash Transaction ID.
     */
    "executeTransaction(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Returns the confirmation status of a transaction.
     * @param hash Transaction ID.
     */
    isConfirmed(hash: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    /**
     * Returns the confirmation status of a transaction.
     * @param hash Transaction ID.
     */
    "isConfirmed(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    makeHash(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "makeHash(address,uint256,bytes)"(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    /**
     * Returns number of confirmations of a transaction.
     * @param hash Transaction ID.
     */
    getConfirmationCount(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Returns number of confirmations of a transaction.
     * @param hash Transaction ID.
     */
    "getConfirmationCount(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Returns list of owners.
     */
    getOwners(overrides?: CallOverrides): Promise<string[]>;

    /**
     * Returns list of owners.
     */
    "getOwners()"(overrides?: CallOverrides): Promise<string[]>;

    /**
     * Returns array with owner addresses, which confirmed transaction.
     * @param hash Transaction ID.
     */
    getConfirmations(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    /**
     * Returns array with owner addresses, which confirmed transaction.
     * @param hash Transaction ID.
     */
    "getConfirmations(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getTransaction(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, boolean, BigNumber, string] & {
        destination: string;
        value: BigNumber;
        data: string;
        executed: boolean;
        timestamp: BigNumber;
        hash: string;
      }
    >;

    "getTransaction(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, boolean, BigNumber, string] & {
        destination: string;
        value: BigNumber;
        data: string;
        executed: boolean;
        timestamp: BigNumber;
        hash: string;
      }
    >;

    getTransactionByIdx(
      idx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, boolean, BigNumber, string] & {
        destination: string;
        value: BigNumber;
        data: string;
        executed: boolean;
        timestamp: BigNumber;
        hash: string;
      }
    >;

    "getTransactionByIdx(uint256)"(
      idx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, boolean, BigNumber, string] & {
        destination: string;
        value: BigNumber;
        data: string;
        executed: boolean;
        timestamp: BigNumber;
        hash: string;
      }
    >;
  };

  filters: {
    Confirmation(sender: string | null, hash: BytesLike | null): EventFilter;

    Deposit(sender: string | null, value: null): EventFilter;

    Execution(hash: BytesLike | null): EventFilter;

    ExecutionFailure(hash: BytesLike | null): EventFilter;

    OwnerAddition(owner: string | null): EventFilter;

    OwnerRemoval(owner: string | null): EventFilter;

    RequirementChange(required: null): EventFilter;

    Revocation(sender: string | null, hash: BytesLike | null): EventFilter;

    Submission(hash: BytesLike | null): EventFilter;
  };

  estimateGas: {
    MAX_OWNER_COUNT(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_OWNER_COUNT()"(overrides?: CallOverrides): Promise<BigNumber>;

    confirmations(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "confirmations(bytes32,address)"(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "hashes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOwner(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isOwner(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "owners(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    required(overrides?: CallOverrides): Promise<BigNumber>;

    "required()"(overrides?: CallOverrides): Promise<BigNumber>;

    transactionCount(overrides?: CallOverrides): Promise<BigNumber>;

    "transactionCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    transactions(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "transactions(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ownerHasConfirmed(
      hash: BytesLike,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ownerHasConfirmed(bytes32,address)"(
      hash: BytesLike,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Allows to add a new owner. Transaction has to be sent by wallet.
     * @param owner Address of new owner to add.
     */
    addOwner(owner: string, overrides?: Overrides): Promise<BigNumber>;

    /**
     * Allows to add a new owner. Transaction has to be sent by wallet.
     * @param owner Address of new owner to add.
     */
    "addOwner(address)"(
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows to remove an owner. Transaction has to be sent by wallet.
     * @param owner Address of owner to remove.
     */
    removeOwner(owner: string, overrides?: Overrides): Promise<BigNumber>;

    /**
     * Allows to remove an owner. Transaction has to be sent by wallet.
     * @param owner Address of owner to remove.
     */
    "removeOwner(address)"(
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows to replace an owner with a new owner. Transaction has to be sent by wallet.
     * @param newOwner Address of new owner.
     * @param owner Address of owner to be replaced.
     */
    replaceOwner(
      owner: string,
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows to replace an owner with a new owner. Transaction has to be sent by wallet.
     * @param newOwner Address of new owner.
     * @param owner Address of owner to be replaced.
     */
    "replaceOwner(address,address)"(
      owner: string,
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows to change the number of required confirmations. Transaction has to be sent by wallet.
     * @param _required Number of required confirmations.
     */
    changeRequirement(
      _required: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows to change the number of required confirmations. Transaction has to be sent by wallet.
     * @param _required Number of required confirmations.
     */
    "changeRequirement(uint256)"(
      _required: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows an owner to submit and confirm a transaction.
     * @param data Transaction data payload.
     * @param destination Transaction target address.
     * @param value Transaction ether value.
     */
    submitTransaction(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows an owner to submit and confirm a transaction.
     * @param data Transaction data payload.
     * @param destination Transaction target address.
     * @param value Transaction ether value.
     */
    "submitTransaction(address,uint256,bytes)"(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows an owner to confirm a transaction.
     * @param hash Transaction ID.
     */
    confirmTransaction(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows an owner to confirm a transaction.
     * @param hash Transaction ID.
     */
    "confirmTransaction(bytes32)"(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows an owner to revoke a confirmation for a transaction.
     * @param hash Transaction ID.
     */
    revokeConfirmation(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows an owner to revoke a confirmation for a transaction.
     * @param hash Transaction ID.
     */
    "revokeConfirmation(bytes32)"(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows anyone to execute a confirmed transaction.
     * @param hash Transaction ID.
     */
    executeTransaction(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows anyone to execute a confirmed transaction.
     * @param hash Transaction ID.
     */
    "executeTransaction(bytes32)"(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Returns the confirmation status of a transaction.
     * @param hash Transaction ID.
     */
    isConfirmed(hash: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns the confirmation status of a transaction.
     * @param hash Transaction ID.
     */
    "isConfirmed(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    makeHash(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "makeHash(address,uint256,bytes)"(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Returns number of confirmations of a transaction.
     * @param hash Transaction ID.
     */
    getConfirmationCount(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Returns number of confirmations of a transaction.
     * @param hash Transaction ID.
     */
    "getConfirmationCount(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Returns list of owners.
     */
    getOwners(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns list of owners.
     */
    "getOwners()"(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns array with owner addresses, which confirmed transaction.
     * @param hash Transaction ID.
     */
    getConfirmations(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Returns array with owner addresses, which confirmed transaction.
     * @param hash Transaction ID.
     */
    "getConfirmations(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTransaction(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTransaction(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTransactionByIdx(
      idx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTransactionByIdx(uint256)"(
      idx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_OWNER_COUNT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "MAX_OWNER_COUNT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    confirmations(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "confirmations(bytes32,address)"(
      arg0: BytesLike,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hashes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOwner(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isOwner(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owners(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "owners(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    required(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "required()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transactionCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "transactionCount()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transactions(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "transactions(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ownerHasConfirmed(
      hash: BytesLike,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ownerHasConfirmed(bytes32,address)"(
      hash: BytesLike,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows to add a new owner. Transaction has to be sent by wallet.
     * @param owner Address of new owner to add.
     */
    addOwner(
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows to add a new owner. Transaction has to be sent by wallet.
     * @param owner Address of new owner to add.
     */
    "addOwner(address)"(
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows to remove an owner. Transaction has to be sent by wallet.
     * @param owner Address of owner to remove.
     */
    removeOwner(
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows to remove an owner. Transaction has to be sent by wallet.
     * @param owner Address of owner to remove.
     */
    "removeOwner(address)"(
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows to replace an owner with a new owner. Transaction has to be sent by wallet.
     * @param newOwner Address of new owner.
     * @param owner Address of owner to be replaced.
     */
    replaceOwner(
      owner: string,
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows to replace an owner with a new owner. Transaction has to be sent by wallet.
     * @param newOwner Address of new owner.
     * @param owner Address of owner to be replaced.
     */
    "replaceOwner(address,address)"(
      owner: string,
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows to change the number of required confirmations. Transaction has to be sent by wallet.
     * @param _required Number of required confirmations.
     */
    changeRequirement(
      _required: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows to change the number of required confirmations. Transaction has to be sent by wallet.
     * @param _required Number of required confirmations.
     */
    "changeRequirement(uint256)"(
      _required: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows an owner to submit and confirm a transaction.
     * @param data Transaction data payload.
     * @param destination Transaction target address.
     * @param value Transaction ether value.
     */
    submitTransaction(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows an owner to submit and confirm a transaction.
     * @param data Transaction data payload.
     * @param destination Transaction target address.
     * @param value Transaction ether value.
     */
    "submitTransaction(address,uint256,bytes)"(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows an owner to confirm a transaction.
     * @param hash Transaction ID.
     */
    confirmTransaction(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows an owner to confirm a transaction.
     * @param hash Transaction ID.
     */
    "confirmTransaction(bytes32)"(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows an owner to revoke a confirmation for a transaction.
     * @param hash Transaction ID.
     */
    revokeConfirmation(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows an owner to revoke a confirmation for a transaction.
     * @param hash Transaction ID.
     */
    "revokeConfirmation(bytes32)"(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows anyone to execute a confirmed transaction.
     * @param hash Transaction ID.
     */
    executeTransaction(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows anyone to execute a confirmed transaction.
     * @param hash Transaction ID.
     */
    "executeTransaction(bytes32)"(
      hash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the confirmation status of a transaction.
     * @param hash Transaction ID.
     */
    isConfirmed(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the confirmation status of a transaction.
     * @param hash Transaction ID.
     */
    "isConfirmed(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    makeHash(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "makeHash(address,uint256,bytes)"(
      destination: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns number of confirmations of a transaction.
     * @param hash Transaction ID.
     */
    getConfirmationCount(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns number of confirmations of a transaction.
     * @param hash Transaction ID.
     */
    "getConfirmationCount(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns list of owners.
     */
    getOwners(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Returns list of owners.
     */
    "getOwners()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Returns array with owner addresses, which confirmed transaction.
     * @param hash Transaction ID.
     */
    getConfirmations(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns array with owner addresses, which confirmed transaction.
     * @param hash Transaction ID.
     */
    "getConfirmations(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTransaction(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTransaction(bytes32)"(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTransactionByIdx(
      idx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTransactionByIdx(uint256)"(
      idx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
