/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ResourceActionsV10Interface extends ethers.utils.Interface {
  functions: {
    "owner()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "setCompaniesContract(address)": FunctionFragment;
    "setPermission(uint8,address,bool)": FunctionFragment;
    "setPermissions(uint8[],address,bool)": FunctionFragment;
    "getPermission(uint8,address)": FunctionFragment;
    "getProduceAction()": FunctionFragment;
    "getDropOffAction()": FunctionFragment;
    "getPickUpAction()": FunctionFragment;
    "getModifyAction()": FunctionFragment;
    "getMoveAction()": FunctionFragment;
    "getTransferCompleteAction()": FunctionFragment;
    "getMeasureAction()": FunctionFragment;
    "getPermissions(address)": FunctionFragment;
    "getAllActions()": FunctionFragment;
    "getCompaniesContract()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCompaniesContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPermission",
    values: [BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPermissions",
    values: [BigNumberish[], string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getPermission",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProduceAction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDropOffAction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPickUpAction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getModifyAction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMoveAction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferCompleteAction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMeasureAction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPermissions",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllActions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCompaniesContract",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCompaniesContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProduceAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDropOffAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPickUpAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getModifyAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMoveAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransferCompleteAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMeasureAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCompaniesContract",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class ResourceActionsV10 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ResourceActionsV10Interface;

  functions: {
    /**
     * Tells the address of the owner return the address of the owner
     */
    owner(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Tells the address of the owner return the address of the owner
     */
    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initialize(
      _multisigWallet: string,
      _companies: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,address)"(
      _multisigWallet: string,
      _companies: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Setters
     */
    setCompaniesContract(
      _companies: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Setters
     */
    "setCompaniesContract(address)"(
      _companies: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setPermission(
      _action: BigNumberish,
      _company: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPermission(uint8,address,bool)"(
      _action: BigNumberish,
      _company: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setPermissions(
      _permissions: BigNumberish[],
      _company: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPermissions(uint8[],address,bool)"(
      _permissions: BigNumberish[],
      _company: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    /**
     * Getters
     */
    getPermission(
      _action: BigNumberish,
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    /**
     * Getters
     */
    "getPermission(uint8,address)"(
      _action: BigNumberish,
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getProduceAction(overrides?: CallOverrides): Promise<[number]>;

    "getProduceAction()"(overrides?: CallOverrides): Promise<[number]>;

    getDropOffAction(overrides?: CallOverrides): Promise<[number]>;

    "getDropOffAction()"(overrides?: CallOverrides): Promise<[number]>;

    getPickUpAction(overrides?: CallOverrides): Promise<[number]>;

    "getPickUpAction()"(overrides?: CallOverrides): Promise<[number]>;

    getModifyAction(overrides?: CallOverrides): Promise<[number]>;

    "getModifyAction()"(overrides?: CallOverrides): Promise<[number]>;

    getMoveAction(overrides?: CallOverrides): Promise<[number]>;

    "getMoveAction()"(overrides?: CallOverrides): Promise<[number]>;

    getTransferCompleteAction(overrides?: CallOverrides): Promise<[number]>;

    "getTransferCompleteAction()"(overrides?: CallOverrides): Promise<[number]>;

    getMeasureAction(overrides?: CallOverrides): Promise<[number]>;

    "getMeasureAction()"(overrides?: CallOverrides): Promise<[number]>;

    getPermissions(
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ]
    >;

    "getPermissions(address)"(
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ]
    >;

    getAllActions(
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number
      ]
    >;

    "getAllActions()"(
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number
      ]
    >;

    getCompaniesContract(overrides?: CallOverrides): Promise<[string]>;

    "getCompaniesContract()"(overrides?: CallOverrides): Promise<[string]>;
  };

  /**
   * Tells the address of the owner return the address of the owner
   */
  owner(overrides?: CallOverrides): Promise<string>;

  /**
   * Tells the address of the owner return the address of the owner
   */
  "owner()"(overrides?: CallOverrides): Promise<string>;

  /**
   * Allows the current owner to transfer control of the contract to a newOwner.
   * @param newOwner The address to transfer ownership to.
   */
  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Allows the current owner to transfer control of the contract to a newOwner.
   * @param newOwner The address to transfer ownership to.
   */
  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initialize(
    _multisigWallet: string,
    _companies: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,address)"(
    _multisigWallet: string,
    _companies: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Setters
   */
  setCompaniesContract(
    _companies: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Setters
   */
  "setCompaniesContract(address)"(
    _companies: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setPermission(
    _action: BigNumberish,
    _company: string,
    _allow: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPermission(uint8,address,bool)"(
    _action: BigNumberish,
    _company: string,
    _allow: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setPermissions(
    _permissions: BigNumberish[],
    _company: string,
    _allow: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPermissions(uint8[],address,bool)"(
    _permissions: BigNumberish[],
    _company: string,
    _allow: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  /**
   * Getters
   */
  getPermission(
    _action: BigNumberish,
    _signatorie: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  /**
   * Getters
   */
  "getPermission(uint8,address)"(
    _action: BigNumberish,
    _signatorie: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getProduceAction(overrides?: CallOverrides): Promise<number>;

  "getProduceAction()"(overrides?: CallOverrides): Promise<number>;

  getDropOffAction(overrides?: CallOverrides): Promise<number>;

  "getDropOffAction()"(overrides?: CallOverrides): Promise<number>;

  getPickUpAction(overrides?: CallOverrides): Promise<number>;

  "getPickUpAction()"(overrides?: CallOverrides): Promise<number>;

  getModifyAction(overrides?: CallOverrides): Promise<number>;

  "getModifyAction()"(overrides?: CallOverrides): Promise<number>;

  getMoveAction(overrides?: CallOverrides): Promise<number>;

  "getMoveAction()"(overrides?: CallOverrides): Promise<number>;

  getTransferCompleteAction(overrides?: CallOverrides): Promise<number>;

  "getTransferCompleteAction()"(overrides?: CallOverrides): Promise<number>;

  getMeasureAction(overrides?: CallOverrides): Promise<number>;

  "getMeasureAction()"(overrides?: CallOverrides): Promise<number>;

  getPermissions(
    _signatorie: string,
    overrides?: CallOverrides
  ): Promise<
    [
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean
    ]
  >;

  "getPermissions(address)"(
    _signatorie: string,
    overrides?: CallOverrides
  ): Promise<
    [
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean
    ]
  >;

  getAllActions(
    overrides?: CallOverrides
  ): Promise<
    [
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number
    ]
  >;

  "getAllActions()"(
    overrides?: CallOverrides
  ): Promise<
    [
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number
    ]
  >;

  getCompaniesContract(overrides?: CallOverrides): Promise<string>;

  "getCompaniesContract()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    /**
     * Tells the address of the owner return the address of the owner
     */
    owner(overrides?: CallOverrides): Promise<string>;

    /**
     * Tells the address of the owner return the address of the owner
     */
    "owner()"(overrides?: CallOverrides): Promise<string>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(
      _multisigWallet: string,
      _companies: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address)"(
      _multisigWallet: string,
      _companies: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Setters
     */
    setCompaniesContract(
      _companies: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Setters
     */
    "setCompaniesContract(address)"(
      _companies: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPermission(
      _action: BigNumberish,
      _company: string,
      _allow: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPermission(uint8,address,bool)"(
      _action: BigNumberish,
      _company: string,
      _allow: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setPermissions(
      _permissions: BigNumberish[],
      _company: string,
      _allow: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPermissions(uint8[],address,bool)"(
      _permissions: BigNumberish[],
      _company: string,
      _allow: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Getters
     */
    getPermission(
      _action: BigNumberish,
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    /**
     * Getters
     */
    "getPermission(uint8,address)"(
      _action: BigNumberish,
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getProduceAction(overrides?: CallOverrides): Promise<number>;

    "getProduceAction()"(overrides?: CallOverrides): Promise<number>;

    getDropOffAction(overrides?: CallOverrides): Promise<number>;

    "getDropOffAction()"(overrides?: CallOverrides): Promise<number>;

    getPickUpAction(overrides?: CallOverrides): Promise<number>;

    "getPickUpAction()"(overrides?: CallOverrides): Promise<number>;

    getModifyAction(overrides?: CallOverrides): Promise<number>;

    "getModifyAction()"(overrides?: CallOverrides): Promise<number>;

    getMoveAction(overrides?: CallOverrides): Promise<number>;

    "getMoveAction()"(overrides?: CallOverrides): Promise<number>;

    getTransferCompleteAction(overrides?: CallOverrides): Promise<number>;

    "getTransferCompleteAction()"(overrides?: CallOverrides): Promise<number>;

    getMeasureAction(overrides?: CallOverrides): Promise<number>;

    "getMeasureAction()"(overrides?: CallOverrides): Promise<number>;

    getPermissions(
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ]
    >;

    "getPermissions(address)"(
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ]
    >;

    getAllActions(
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number
      ]
    >;

    "getAllActions()"(
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number
      ]
    >;

    getCompaniesContract(overrides?: CallOverrides): Promise<string>;

    "getCompaniesContract()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    OwnershipTransferred(previousOwner: null, newOwner: null): EventFilter;
  };

  estimateGas: {
    /**
     * Tells the address of the owner return the address of the owner
     */
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Tells the address of the owner return the address of the owner
     */
    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    initialize(
      _multisigWallet: string,
      _companies: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,address)"(
      _multisigWallet: string,
      _companies: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Setters
     */
    setCompaniesContract(
      _companies: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Setters
     */
    "setCompaniesContract(address)"(
      _companies: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setPermission(
      _action: BigNumberish,
      _company: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPermission(uint8,address,bool)"(
      _action: BigNumberish,
      _company: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setPermissions(
      _permissions: BigNumberish[],
      _company: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPermissions(uint8[],address,bool)"(
      _permissions: BigNumberish[],
      _company: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    /**
     * Getters
     */
    getPermission(
      _action: BigNumberish,
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Getters
     */
    "getPermission(uint8,address)"(
      _action: BigNumberish,
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProduceAction(overrides?: CallOverrides): Promise<BigNumber>;

    "getProduceAction()"(overrides?: CallOverrides): Promise<BigNumber>;

    getDropOffAction(overrides?: CallOverrides): Promise<BigNumber>;

    "getDropOffAction()"(overrides?: CallOverrides): Promise<BigNumber>;

    getPickUpAction(overrides?: CallOverrides): Promise<BigNumber>;

    "getPickUpAction()"(overrides?: CallOverrides): Promise<BigNumber>;

    getModifyAction(overrides?: CallOverrides): Promise<BigNumber>;

    "getModifyAction()"(overrides?: CallOverrides): Promise<BigNumber>;

    getMoveAction(overrides?: CallOverrides): Promise<BigNumber>;

    "getMoveAction()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTransferCompleteAction(overrides?: CallOverrides): Promise<BigNumber>;

    "getTransferCompleteAction()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMeasureAction(overrides?: CallOverrides): Promise<BigNumber>;

    "getMeasureAction()"(overrides?: CallOverrides): Promise<BigNumber>;

    getPermissions(
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPermissions(address)"(
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllActions(overrides?: CallOverrides): Promise<BigNumber>;

    "getAllActions()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCompaniesContract(overrides?: CallOverrides): Promise<BigNumber>;

    "getCompaniesContract()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Tells the address of the owner return the address of the owner
     */
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Tells the address of the owner return the address of the owner
     */
    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Allows the current owner to transfer control of the contract to a newOwner.
     * @param newOwner The address to transfer ownership to.
     */
    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _multisigWallet: string,
      _companies: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,address)"(
      _multisigWallet: string,
      _companies: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Setters
     */
    setCompaniesContract(
      _companies: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Setters
     */
    "setCompaniesContract(address)"(
      _companies: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setPermission(
      _action: BigNumberish,
      _company: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPermission(uint8,address,bool)"(
      _action: BigNumberish,
      _company: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setPermissions(
      _permissions: BigNumberish[],
      _company: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPermissions(uint8[],address,bool)"(
      _permissions: BigNumberish[],
      _company: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    /**
     * Getters
     */
    getPermission(
      _action: BigNumberish,
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Getters
     */
    "getPermission(uint8,address)"(
      _action: BigNumberish,
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProduceAction(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getProduceAction()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDropOffAction(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getDropOffAction()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPickUpAction(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getPickUpAction()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getModifyAction(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getModifyAction()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMoveAction(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getMoveAction()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTransferCompleteAction(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTransferCompleteAction()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMeasureAction(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getMeasureAction()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPermissions(
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPermissions(address)"(
      _signatorie: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllActions(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getAllActions()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCompaniesContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCompaniesContract()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
